routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
// Admin Routes
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    // Dashboard
    Route::get('/dashboard','DashboardController@index')->name('dashboard.index');
    // Category
    Route::prefix('category')->group(function () {
        Route::get('/','CategoryController@index')->name('category.index');
        Route::post('/','CategoryController@store')->name('category.store');
        Route::delete('/{category}','CategoryController@destroy')->name('category.delete');
        Route::get('/{category}','CategoryController@edit')->name('category.edit');
        Route::put('/{category}','CategoryController@update')->name('category.update');
    });
    // Tag
    Route::prefix('tag')->group(function () {
        Route::get('/','TagController@index')->name('tag.index');
        Route::post('/','TagController@store')->name('tag.store');
        Route::delete('/{tag}','TagController@destroy')->name('tag.delete');
        Route::get('/{tag}','TagController@edit')->name('tag.edit');
        Route::put('/{tag}','TagController@update')->name('tag.update');
    });
    // Post
    Route::resource('post','PostController');
});
// Site Routes
Route::get('/','HomeController@index')->name('home.index');

app/Category.php
<?php

namespace App;


class Category extends BaseModel
{
// Relations
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.category.index',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        Category::create($request->validate([
            'title' => 'required|min:3|unique:categories,title'
        ]));

        return redirect()->route('admin.category.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::all();
        return view('admin.category.index',compact('category','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Category $category)
    {
        $category->update($request->validate([
            'title' => 'required|min:3|unique:categories,title'
        ]));

        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('admin.category.index');
    }
}

resources/views/admin/category/index.blade.php
@extends('admin.index')

@section('title','Category')

@section('content-header','دسته بندی')

@section('content')

    <div class="row">
        <div class="col-xs-12">

            <div class="box">
                <form action="<?= isset($category) ? route('admin.category.update', $category) : route('admin.category.store')  ?>"
                      method="post">
                    @if(isset($category))
                        @method('PUT')
                    @endif
                    @csrf
                    <div class="box-header">
                        <h3 class="box-title"><?= isset($category) ? 'ویرایش دسته بندی :' : 'ایجاد دسته بندی جدید :' ?></h3>
                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 300px;">
                                <input name="title" class="form-control pull-left" placeholder="نام دسته را وارد نمایید"
                                       value="<?= isset($category) ? $category->title : old('title')?>" type="text">
                                <div class="input-group-btn">
                                    <button type="submit"
                                            class="btn btn-primary"><?= isset($category) ? 'ویرایش' : 'افزودن' ?></button>
                                    @if( isset($category) )
                                        <a href="{{ route('admin.category.index') }}"  class="btn btn-default">بازگشت</a>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
               @include('admin.layouts.error')
            <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table direction table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>عنوان</th>
                            <th>تعداد مقالات</th>
                            <th>اخرین ویرایش</th>
                            <th>عملیات</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if( !empty($categories) )
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $category->title }}</td>
                                    <td>{{ $category->posts()->count() }}</td>
                                    <td>{{ jdate($category->updated_at)->ago() }}</td>
                                    <td>
                                        <div class="btn-group">
                                            <form action="{{ route('admin.category.delete',$category) }}" method="post">
                                                @method('DELETE')
                                                @csrf
                                                <a href="{{ route('admin.category.edit',$category) }}"
                                                   class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                                <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td><h3 class="text-center">'دسته بندی وجود ندارد'</h3></td>
                            </tr>
                        @endif

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

@endsection