routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
// Admin Routes
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    // Dashboard
    Route::get('/dashboard','DashboardController@index')->name('dashboard.index');
    // Category
    Route::prefix('category')->group(function () {
        Route::get('/','CategoryController@index')->name('category.index');
        Route::post('/','CategoryController@store')->name('category.store');
        Route::delete('/{category}','CategoryController@destroy')->name('category.delete');
        Route::get('/{category}','CategoryController@edit')->name('category.edit');
        Route::put('/{category}','CategoryController@update')->name('category.update');
    });
    // Tag
    Route::prefix('tag')->group(function () {
        Route::get('/','TagController@index')->name('tag.index');
        Route::post('/','TagController@store')->name('tag.store');
        Route::delete('/{tag}','TagController@destroy')->name('tag.delete');
        Route::get('/{tag}','TagController@edit')->name('tag.edit');
        Route::put('/{tag}','TagController@update')->name('tag.update');
    });
    // Post
    Route::resource('post','PostController');
});
// Site Routes
Route::get('/','HomeController@index')->name('home.index');

app/Post.php
<?php

namespace App;

class Post extends BaseModel
{
 // Relations
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Post;
use App\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('admin.post.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.post.create',compact('categories','tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Post $post , Request $request)
    {
        $request->validate([
           'title' => 'required|min:3|unique:posts',
           'category' => 'required',
           'description' => 'required',
           'image' => 'required|image'
        ]);
        $post = $post->create([
            'title' => $request->title,
            'category_id' => $request->category,
            'description' => $request->description,
        ]);

        $post->tags()->sync($request->tags);

        $image = $request->file('image');
        $image_name = $post->id.'_'.time().'.jpg';
        $destination = public_path().'/upload/post/'.$post->id;
        File::makeDirectory($destination,0777,true,true);
        if ($image->move($destination,$image_name)) {
            $post->update([
               'image' => $image_name
            ]);
        }else {
            return redirect()->route('admin.post.index')->with('image_error','مقاله ثبت شد ولی تصویر اپلود نشد !');
        }
        return redirect()->route('admin.post.index')->with('image_success','مقاله با موفقیت ثبت شد !');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        // delete post
        $post->delete();
        // delete image post
        $path = public_path("upload/post/$post->id");
        if (File::exists($path)) {
            File::deleteDirectory($path);
        }
        // delete tags post
        $post->tags()->detach($post->tags);

        return redirect()->back();
    }
}

resources/views/admin/post/create.blade.php
@extends('admin.index')

@section('title','Post | Create')

@section('content-header','ایجاد مقاله')

@section('css')
    <!-- select2 -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/select2/dist/css/select2.min.css') }}">
@endsection

@section('content')
    <div class="row">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">ایجاد مقاله </h3>
            </div>
            <!-- /.box-header -->
            @include('admin.layouts.error')
            <!-- form start -->
            <form role="form" action="{{ route('admin.post.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="box-body">
                    <div class="form-group col-lg-6">
                        <label for="title">عنوان :</label>
                        <input name="title" type="text" class="form-control " id="title" value="{{ old('title') }}" placeholder="عنوان مقاله">
                    </div>
                    <div class="form-group">
                        <label for="category">دسته بندی :</label>
                        <select id="category" name="category" class="form-control select2" style="width: 50%;padding: 0 5px">
                            <option value="">انتخاب دسته بندی</option>
                            @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->title }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="editor1">متن مقاله :</label>
                        <textarea class="form-control" id="editor1" name="description" rows="10" cols="80">{{ old('description') }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="tags">برچسب :</label>
                        <select name="tags[]" id="tags" class="form-control select2" multiple="multiple" data-placeholder="انتخاب برچسب"
                                style="width: 50%;">
                            @foreach($tags as $tag)
                                <option value="{{ $tag->id }}">{{ $tag->title }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-lg-3">
                        <label for="image">تصویر : </label>
                        <input name="image" id="image" class="form-control" type="file">
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">ارسال</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('js')
    <!-- select2 -->
    <script src="{{ asset('admin/bower_components/select2/dist/js/select2.min.js') }}"></script>
    <!-- CK Editor -->
    <script src="{{ asset('admin/bower_components/ckeditor/ckeditor.js') }}"></script>
@endsection

resources/views/admin/post/index.blade.php
@extends('admin.index')

@section('title','Post')

@section('content-header','مقالات')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                @csrf
                <div class="box-header">
                    <h3 class="box-title">ایجاد مقاله جدید :</h3>
                    <div class="box-tools">
                        <a class="btn btn-primary" href="{{ route('admin.post.create') }}">افزودن</a>
                    </div>
                </div>
                @if( $errors->any() )
                    <div class="callout callout-danger">
                        <ul>
                            @foreach( $errors->all() as $error )
                                <li> {{ $error }} </li>
                            @endforeach
                        </ul>
                    </div>
                 @endif
                @if( session()->has('image_success') )
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close pull-left" data-dismiss="alert" aria-hidden="true">×</button>
                        <h6><i class="icon fa fa-check"></i>{{ session()->get('image_success') }}</h6>
                    </div>
                @endif
                @if( session()->has('image_error') )
                    <div class="alert alert-error alert-dismissible">
                        <button type="button" class="close pull-left" data-dismiss="alert" aria-hidden="true">×</button>
                        <h6><i class="icon fa fa-ban"></i>{{ session()->get('image_error') }}</h6>
                    </div>
                @endif
            <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    @if( $posts )
                        <table class="table direction table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>عنوان</th>
                                <th>تعداد پیام ها</th>
                                <th>اخرین ویرایش</th>
                                <th>عملیات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($posts as $post)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $post->title }}</td>
                                    <td>20</td>
                                    <td>{{ jdate($post->updated_at)->ago() }}</td>
                                    <td>
                                        <div class="btn-group">
                                            <form action="{{ route('admin.post.destroy',$post) }}" method="post">
                                                @method('DELETE')
                                                @csrf
                                                <a href="{{ route('admin.post.edit',$post) }}"
                                                   class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                                <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <h1 class="text-center">مقاله ایی وجود ندارد !</h1>
                    @endif
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <!-- /.box -->
    </div>
    </div>

@endsection