routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
// Admin Routes
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    // Dashboard
    Route::get('/dashboard','DashboardController@index')->name('dashboard.index');
    // Category
    Route::prefix('category')->group(function () {
        Route::get('/','CategoryController@index')->name('category.index');
        Route::post('/','CategoryController@store')->name('category.store');
        Route::delete('/{category}','CategoryController@destroy')->name('category.delete');
        Route::get('/{category}','CategoryController@edit')->name('category.edit');
        Route::put('/{category}','CategoryController@update')->name('category.update');
    });
    // Tag
    Route::prefix('tag')->group(function () {
        Route::get('/','TagController@index')->name('tag.index');
        Route::post('/','TagController@store')->name('tag.store');
        Route::delete('/{tag}','TagController@destroy')->name('tag.delete');
        Route::get('/{tag}','TagController@edit')->name('tag.edit');
        Route::put('/{tag}','TagController@update')->name('tag.update');
    });
    // Post
    Route::resource('post','PostController');
});
// Site Routes
Route::get('/','HomeController@index')->name('home.index');

resources/views/admin/layouts/error.blade.php
@if( $errors->any() )
    <div class="callout callout-danger">
        <ul>
            @foreach( $errors->all() as $error )
                <li> {{ $error }} </li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.3.8
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

resources/views/admin/layouts/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-right image">
          <img src="{{ asset('admin/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>محمد حسن زرخوانی</p>
          <a href="#"><i class="fa fa-circle text-success"></i> انلاین </a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li><a href="{{ route('admin.dashboard.index') }}"><i class="fa fa-dashboard"></i> <span>داشبورد</span></a></li>
        <li><a href="{{ route('admin.category.index') }}"><i class="fa fa-th-list"></i> <span>دسته بندی</span></a></li>
          <li><a href="{{ route('admin.post.index') }}"><i class="fa fa-sticky-note"></i> <span>مقالات</span></a></li>
          <li><a href="{{ route('admin.tag.index') }}"><i class="fa fa-tags"></i> <span>برچسب</span></a></li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>